<?php

namespace escape\info\assetbundles;

use Craft;
use craft\web\AssetBundle;

class AdspaceBannerBundle extends AssetBundle
{

    public function init()
    {

        $this->sourcePath = '@escapeinfoplugin/web/assets/dist/adspace';

        $this->depends = [
            PlaygroundBundle::class,
        ];

        $this->js = [
            'adspace-banner.js',
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

}
