<?php

namespace escape\info\assetbundles;

use Craft;
use craft\web\AssetBundle;

class ShoutoutsButtonBundle extends AssetBundle
{

    public function init()
    {

        $this->sourcePath = '@escapeinfoplugin/web/assets/dist';

        $this->js = [
            'shoutouts-button.js',
        ];

        $this->css = [
            'shoutouts-button.css',
        ];

        parent::init(); // TODO: Change the autogenerated stub
    }

}
