<?php

namespace escape\info;

use Craft;
use craft\base\Plugin;
use craft\events\RegisterComponentTypesEvent;
use craft\events\RegisterTemplateRootsEvent;
use craft\services\Fields;
use craft\web\twig\variables\CraftVariable;
use craft\web\View;

use escape\info\fields\AdspaceSelect;
use escape\info\models\Settings;
use escape\info\services\Adspace;
use escape\info\web\twig\EscapeInfoTwigExtension;
use escape\info\web\twig\variables\EscapeInfoVariable;

use yii\base\Event;

/**
 * @property Adspace $adspace
 */
class EscapeInfo extends Plugin
{

    /**
     * @inheritdoc
     */
    public function init()
    {
        
        Craft::setAlias('@escapeinfoplugin', __DIR__);

        parent::init();

        // Base template directory
        Event::on(View::class, View::EVENT_REGISTER_CP_TEMPLATE_ROOTS, function (RegisterTemplateRootsEvent $e) {
            if (is_dir($baseDir = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates')) {
                $e->roots[$this->id] = $baseDir;
            }
        });

        // Register services
        $this->setComponents([
            'adspace' => Adspace::class,
        ]);

        // Register module variable
        Event::on(
            CraftVariable::class,
            CraftVariable::EVENT_INIT,
            function (Event $event) {
                $variable = $event->sender;
                $variable->set('escapeinfo', EscapeInfoVariable::class);
            }
        );

        // Register Twig extension
        //Craft::$app->getView()->registerTwigExtension(new EscapeInfoTwigExtension());

        // Register custom fields
        Event::on(Fields::class, Fields::EVENT_REGISTER_FIELD_TYPES, function (RegisterComponentTypesEvent $event) {
            $event->types[] = AdspaceSelect::class;
        });
    }

    /**
     * @return Settings
     */
    public function createSettingsModel()
    {
        return new Settings();
    }

    /**
     * @return Settings
     */
    public function getSettings()
    {
        return parent::getSettings(); // TODO: Change the autogenerated stub
    }

}
