<?php

namespace escape\info;

use Craft;
use craft\base\Plugin;
use craft\events\RegisterComponentTypesEvent;
use craft\events\RegisterTemplateRootsEvent;
use craft\events\TemplateEvent;
use craft\helpers\Html;
use craft\helpers\Json;
use craft\i18n\PhpMessageSource;
use craft\services\Fields;
use craft\web\twig\variables\CraftVariable;
use craft\web\View;

use escape\info\fields\AdspaceSelect;
use escape\info\models\Settings;
use escape\info\services\Adspace;
use escape\info\web\twig\EscapeInfoTwigExtension;
use escape\info\web\twig\variables\EscapeInfoVariable;

use yii\base\Event;

/**
 * @property Adspace $adspace
 */
class EscapeInfo extends Plugin
{

    /**
     * @inheritdoc
     */
    public function init()
    {
        
        Craft::setAlias('@escapeinfoplugin', __DIR__);

        parent::init();

        // Base template directory
        Event::on(View::class, View::EVENT_REGISTER_CP_TEMPLATE_ROOTS, function (RegisterTemplateRootsEvent $e) {
            if (is_dir($baseDir = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates')) {
                $e->roots[$this->id] = $baseDir;
            }
        });

        // Translations
        Craft::$app->i18n->translations['escape-info'] = [
            'class' => PhpMessageSource::class,
            'sourceLanguage' => 'en',
            'basePath' => __DIR__ . '/translations',
            'allowOverrides' => true,
        ];

        // Register services
        $this->setComponents([
            'adspace' => Adspace::class,
        ]);

        // Register module variable
        Event::on(
            CraftVariable::class,
            CraftVariable::EVENT_INIT,
            function (Event $event) {
                $variable = $event->sender;
                $variable->set('escapeinfo', EscapeInfoVariable::class);
            }
        );

        // Register Twig extension
        //Craft::$app->getView()->registerTwigExtension(new EscapeInfoTwigExtension());

        // Register custom fields
        Event::on(Fields::class, Fields::EVENT_REGISTER_FIELD_TYPES, function (RegisterComponentTypesEvent $event) {
            $event->types[] = AdspaceSelect::class;
        });

        $isSiteRequest = Craft::$app->getRequest()->getIsSiteRequest();
        if ($isSiteRequest) {
            Event::on(
                View::class,
                View::EVENT_AFTER_RENDER_PAGE_TEMPLATE,
                function (TemplateEvent $event) {
                    \preg_match_all('/(<!-- playground-banner:)(.*)( -->)/', $event->output, $matches);
                    if (!empty($matches[0] ?? null)) {
                        for ($i = 0; $i < \count($matches[0]); $i++) {
                            $match = $matches[0][$i];
                            $data = Json::decodeIfJson($matches[2][$i]);
                            $ad = $data['ad'];
                            $attributes = $data['attributes'] ?? [];
                            try {
                                $html = Html::modifyTagAttributes(EscapeInfo::getInstance()->adspace->renderBanner($ad['uid'], $ad['siteUid']), $attributes);
                            } catch (\Throwable $e) {
                                $html = '';
                            }
                            $event->output = \str_replace($match, $html, $event->output);
                        }
                    }
                }
            );
        }

        Craft::$app->view->hook('escape-info-head', function(array &$context) {
            $theme = $this->getSettings()->theme;
            return Craft::$app->getView()->renderTemplate('escape-info/_components/playground/playground-theme.twig', ['theme' => $theme], View::TEMPLATE_MODE_CP);
        });

    }

    /**
     * @return Settings
     */
    public function createSettingsModel()
    {
        return new Settings();
    }

    /**
     * @return Settings
     */
    public function getSettings()
    {
        return parent::getSettings(); // TODO: Change the autogenerated stub
    }

}
