<?php

namespace escape\info;

use Craft;
use craft\base\Plugin;
use craft\events\RegisterComponentTypesEvent;
use craft\events\RegisterTemplateRootsEvent;
use craft\events\RegisterUrlRulesEvent;
use craft\events\TemplateEvent;
use craft\helpers\Html;
use craft\helpers\Json;
use craft\i18n\PhpMessageSource;
use craft\services\Fields;
use craft\web\twig\variables\CraftVariable;
use craft\web\UrlManager;
use craft\web\View;

use escape\info\assetbundles\AdspaceBannersBundle;
use escape\info\fields\AdspaceSelect;
use escape\info\models\Settings;
use escape\info\services\Adspace;
use escape\info\web\twig\EscapeInfoTwigExtension;
use escape\info\web\twig\variables\EscapeInfoVariable;

use yii\base\Event;

/**
 * @property Adspace $adspace
 */
class EscapeInfo extends Plugin
{

    /**
     * @inheritdoc
     */
    public function init()
    {

        Craft::setAlias('@escapeinfoplugin', __DIR__);

        parent::init();

        // Base template directory
        Event::on(View::class, View::EVENT_REGISTER_CP_TEMPLATE_ROOTS, function (RegisterTemplateRootsEvent $e) {
            if (is_dir($baseDir = $this->getBasePath() . DIRECTORY_SEPARATOR . 'templates')) {
                $e->roots[$this->id] = $baseDir;
            }
        });

        // Translations
        Craft::$app->i18n->translations['escape-info'] = [
            'class' => PhpMessageSource::class,
            'sourceLanguage' => 'en',
            'basePath' => __DIR__ . '/translations',
            'allowOverrides' => true,
        ];

        // Register services
        $this->setComponents([
            'adspace' => Adspace::class,
        ]);

        // Register module variable
        Event::on(
            CraftVariable::class,
            CraftVariable::EVENT_INIT,
            function (Event $event) {
                $variable = $event->sender;
                $variable->set('escapeinfo', EscapeInfoVariable::class);
            }
        );

        // Register Twig extension
        Craft::$app->getView()->registerTwigExtension(new EscapeInfoTwigExtension());

        // Register custom fields
        Event::on(Fields::class, Fields::EVENT_REGISTER_FIELD_TYPES, function (RegisterComponentTypesEvent $event) {
            $event->types[] = AdspaceSelect::class;
        });

        // Add theme CSS
        Craft::$app->view->hook('escape-info-head', function (array &$context) {
            $theme = $this->getSettings()->theme;
            return Craft::$app->getView()->renderTemplate('escape-info/_components/playground/playground-theme.twig', ['theme' => $theme], View::TEMPLATE_MODE_CP);
        });

        Event::on(
            UrlManager::class,
            UrlManager::EVENT_REGISTER_SITE_URL_RULES,
            function (RegisterUrlRulesEvent $event) {
                $event->rules['playground/get-shoutouts-html'] = 'escape-info/adspace/get-shoutouts-html';
                $event->rules['playground/get-popup-html'] = 'escape-info/adspace/get-popup-html';
                $event->rules['playground/get-banner-html'] = 'escape-info/adspace/get-banner-html';
            }
        );

    }

    /**
     * @return Settings
     */
    public function createSettingsModel(): ?\craft\base\Model
    {
        return new Settings();
    }

    /**
     * @return Settings
     */
    public function getSettings(): ?\craft\base\Model
    {
        return parent::getSettings(); // TODO: Change the autogenerated stub
    }

}
